services:
  # A Docker web service
  - type: web
    name: spirit-and-life
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app --host 0.0.0.0 --port $PORT


# services:
#  - name: 
#    env: python
#    buildCommand: pip install -r requirements.txt
#    startCommand: uvicorn __init__:router --reload --host 0.0.0.0 --port 80